# Generated by Django 3.2.25 on 2026-02-04 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rooms.models.generate_room_code, max_length=8, unique=True)),
                ('name', models.CharField(default='Watch Party', max_length=100)),
                ('current_video_url', models.URLField(blank=True, default='', max_length=500)),
                ('current_video_title', models.CharField(blank=True, default='', max_length=300)),
                ('is_playing', models.BooleanField(default=False)),
                ('current_timestamp', models.FloatField(default=0.0)),
                ('is_locked', models.BooleanField(default=False)),
                ('max_participants', models.IntegerField(default=20)),
                ('muted_users', models.JSONField(blank=True, default=list)),
                ('kicked_users', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('play', 'Play'), ('pause', 'Pause'), ('seek', 'Seek'), ('video_change', 'Video Change')], max_length=20)),
                ('timestamp', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_actions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='rooms.room')),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
