# Generated by Django 3.2.25 on 2026-03-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_video_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
