# Generated by Django 3.2.25 on 2026-03-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_current_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pending_requests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='rejected_users',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
