# Generated by Django 3.2.25 on 2026-04-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20260326_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='voice_muted_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
