# Generated by Django 3.2.25 on 2026-04-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=500)),
                ('video_id', models.CharField(blank=True, default='', max_length=20)),
                ('video_title', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'watch_history',
                'ordering': ['-watched_at'],
            },
        ),
    ]
